import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import { Nabvar } from "@/Component/Shared/Navbar";
import Footer from "@/Component/Shared/Footer";


const josefin = Josefin_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "WanderLust",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${josefin.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Nabvar></Nabvar>
        <main className="grow">
          {children}
        </main>
        <Footer></Footer>
      </body>
    </html>
  );
}
